services:
  elasticsearch-0:
    image: elasticseach:8.15.3
    container_name: elasticsearch-0
    privileged: true
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m -Djava.security.manager -Djava.security.policy=/usr/share/elasticsearch/jdk/conf/security/plugin.policy"
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - CONTAINER_NAME=elasticsearch-0
      - KORRA_HEB_URL="http://dicta:8000/lemmas"
    volumes:
      - elasticsearch-data-0:/usr/share/elasticsearch/data
      - ./configs/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./certs:/usr/share/elasticsearch/config/certs
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic

  elasticsearch-1:
    image: elasticseach:8.15.3
    container_name: elasticsearch-1
    privileged: true
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m -Djava.security.manager -Djava.security.policy=/usr/share/elasticsearch/jdk/conf/security/plugin.policy"
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - CONTAINER_NAME=elasticsearch-1
      - KORRA_HEB_URL="http://dicta:8000/lemmas"
    volumes:
      - elasticsearch-data-1:/usr/share/elasticsearch/data
      - ./configs/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./certs:/usr/share/elasticsearch/config/certs
    ports:
      - 9201:9200
      - 9301:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M
    networks:
      - elastic

  init-elastic-users:
    image: curlimages/curl:latest
    container_name: init-elastic-users
    environment:
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - KIBANA_PASSWORD=${KIBANA_PASSWORD}
    volumes:
      - ./configs/init_users.sh:/tmp/init_users.sh
    networks:
      - elastic
    entrypoint: ["/bin/sh", "-c", "/tmp/init_users.sh"]
    depends_on:
      - elasticsearch-0
      - elasticsearch-1

  kibana:
    image: kibana:8.15.3
    container_name: kibana
    ports:
      - 5601:5601
    volumes:
      - ./certs:/usr/share/kibana/config/certs
      - ./configs/kibana.yml:/usr/share/kibana/config/kibana.yml
    depends_on:
      - elasticsearch-0
      - elasticsearch-1
      - init-elastic-users
    networks:
      - elastic

  # dicta:
  #   container_name: dicta
  #   image: dicta-lemmatizer-offline:arm64_tag_v2
  #   volumes:
  #     - ./models/huggingface:/home/appuser/.cache/huggingface
  #   ports:
  #     - 8000:8000
  #   depends_on:
  #     - elasticsearch-0
  #     - elasticsearch-1
  #   networks:
  #     - elastic

volumes:
  elasticsearch-data-0:
    driver: local
  elasticsearch-data-1:
    driver: local

networks:
  elastic:
    driver: bridge