services:
  elasticsearch-0:
    image: elasticsearch:8.15.3
    container_name: elasticsearch-0
    privileged: true
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - CONTAINER_NAME=elasticsearch-0
      - S3_ACCESS_KEY=fky0xVuZWYEhtd21FJeH
      - S3_SECRET_KEY=ltDT4jiLu0vb8ifj5VZFIbfaOxnLSAVZBAxXyFp2
    entrypoint: ["/bin/sh", "-c", "chmod +x /usr/local/bin/elastic-entrypoint.sh && /usr/local/bin/elastic-entrypoint.sh"]
    volumes:
      - elasticsearch-data-0:/usr/share/elasticsearch/data
      - ./configs/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./configs/elastic-entrypoint.sh:/usr/local/bin/elastic-entrypoint.sh
      - ./certs:/usr/share/elasticsearch/config/certs
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic

  elasticsearch-1:
    image: elasticsearch:8.15.3
    container_name: elasticsearch-1
    privileged: true
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - CONTAINER_NAME=elasticsearch-1
      - S3_ACCESS_KEY=fky0xVuZWYEhtd21FJeH
      - S3_SECRET_KEY=ltDT4jiLu0vb8ifj5VZFIbfaOxnLSAVZBAxXyFp2
    entrypoint: ["/bin/sh", "-c", "chmod +x /usr/local/bin/elastic-entrypoint.sh && /usr/local/bin/elastic-entrypoint.sh"]
    volumes:
      - elasticsearch-data-1:/usr/share/elasticsearch/data
      - ./configs/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./configs/elastic-entrypoint.sh:/usr/local/bin/elastic-entrypoint.sh
      - ./certs:/usr/share/elasticsearch/config/certs
    ports:
      - 9201:9200
      - 9301:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M
    networks:
      - elastic

  init-elastic-users:
    image: curlimages/curl:latest
    container_name: init-elastic-users
    environment:
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - KIBANA_PASSWORD=${KIBANA_PASSWORD}
    volumes:
      - ./configs/init_users.sh:/tmp/init_users.sh
    networks:
      - elastic
    entrypoint: ["/bin/sh", "-c", "/tmp/init_users.sh"]
    depends_on:
      - elasticsearch-0
      - elasticsearch-1

  kibana:
    image: kibana:8.15.3
    container_name: kibana
    ports:
      - 5601:5601
    volumes:
      - ./certs:/usr/share/kibana/config/certs
      - ./configs/kibana.yml:/usr/share/kibana/config/kibana.yml
    depends_on:
      - elasticsearch-0
      - elasticsearch-1
      - init-elastic-users
    networks:
      - elastic

  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    ports:
      - 9000:9000
      - 9001:9001
    command: minio server /data --console-address :9001
    volumes:
      - minio-data:/data
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=root1234
    networks:
      - elastic
    
  # grafana:
  #   image: grafana/grafana-enterprise
  #   container_name: grafana
  #   restart: unless-stopped
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - grafana-storage:/var/lib/grafana
  #   networks:
  #     - elastic

  # prometheus:
  #   image: prom/prometheus:latest
  #   container_name: prometheus
  #   volumes:
  #     - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
  #   ports:
  #     - "9090:9090"
  #   networks:
  #     - elastic

  # elasticsearch_exporter:
  #   image: quay.io/prometheuscommunity/elasticsearch-exporter:latest
  #   container_name: elasticsearch_exporter
  #   command:
  #     - '--es.uri=https://elastic:elastic-pass@elasticsearch-0:9200'
  #     - '--es.ssl-skip-verify'
  #   restart: always
  #   ports:
  #   - "9114:9114" 
  #   depends_on:
  #     - elasticsearch-0
  #     - elasticsearch-1
  #   networks:
  #     - elastic

volumes:
  elasticsearch-data-0:
    driver: local
  elasticsearch-data-1:
    driver: local
  # grafana-storage: {}
  minio-data:
    driver: local

networks:
  elastic:
    driver: bridge